{
  "apiVersion": 1,
  "datasources": [
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://victoriametrics:8428",
        "access":"proxy",
        "editable": true,
        "orgId": 1,
        "version": 1
      }
  ]
}